# Generated by Django 4.2 on 2023-05-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0002_alter_author_author_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
